GeoDjango/geodjango/core/urls.py
from django.urls import path

from . import views as v

app_name = 'core'

urlpatterns = [
    path('', v.index, name='index'),
    path('mapa/', v.mapa, name='mapa'),
]

GeoDjango/geodjango/mun/urls.py
from django.urls import path
from . import views as v

app_name = 'mun'

urlpatterns = [
    path('geojson/', v.munGeoJson.as_view(),name='mun_geojson')
]

GeoDjango/geodjango/points/urls.py
from django.urls import path
from . import views as v

app_name = 'points'

urlpatterns = [
    path('geojson/', v.pocosGeoJson.as_view(),name='poco_geojson')
]

GeoDjango/geodjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('geodjango.core.urls')),
    path('points/', include('geodjango.points.urls')),
    path('mun/', include('geodjango.mun.urls')),
    path('admin/', admin.site.urls),
]

GeoDjango/geodjango/core/models.py
from django.db import models

# Create your models here.

GeoDjango/geodjango/mun/models.py
# This is an auto-generated Django model module created by ogrinspect.
from django.contrib.gis.db import models


class municipio_pb(models.Model):
    nome = models.CharField('nome',max_length=40)
    cod_ibge_m = models.CharField('código IBGE',max_length=20)
    geom = models.MultiPolygonField('geom',srid=4326)

    def __str__(self):
        return self.nome

    @property
    def popup_content(self):
        popup = f'<span>Nome:{self.nome} </span>'
        popup += f'<span>Cod_IBGE:{self.cod_ibge_m} </span>'

        return popup

GeoDjango/geodjango/points/models.py
# This is an auto-generated Django model module created by ogrinspect.
from django.contrib.gis.db import models
from django.template.defaultfilters import date


class pocos(models.Model):
    proprietario = models.CharField("proprietario", max_length=254)
    orgao = models.CharField("orgao", max_length=254)
    data_perfuracao = models.DateField("data_perfuracao")
    profundidade = models.FloatField("profundidade")
    q_m3h = models.FloatField("q_m3h")
    equipamento = models.CharField("equipamento", max_length=254)
    geom = models.PointField("geom", srid=4326)

    def __str__(self):
        return self.proprietario

    @property
    def popup_content(self):
        popup = f'<span>Proprietario:{self.proprietario} </span>'
        popup += f'<span>Órgão:{self.orgao} </span>'
        popup += f'<span>Proprietario:{self.profundidade} </span>'
        popup += f'<span>Profundidade (m):{self.q_m3h} </span>'
        popup += f'<span>Equipamento:{self.equipamento} </span>'
        popup += f"<span>Data de Perfuração:{self.data_perfuracao, 'd/m/Y'} </span>"

        return popup

GeoDjango/geodjango/core/views.py
from django.db.models import Max
from django.shortcuts import render

def index(request):
    return render(request, 'core/index.html')


def mapa(request):
    return render(request, 'core/mapa.html')

GeoDjango/geodjango/mun/views.py
from django.shortcuts import render

from djgeojson.views import GeoJSONLayerView
from .models import municipio_pb

class munGeoJson(GeoJSONLayerView):
    model = municipio_pb
    properties = ('popup_content',)

GeoDjango/geodjango/points/views.py
from django.shortcuts import render
from djgeojson.views import GeoJSONLayerView
from .models import pocos

class pocosGeoJson(GeoJSONLayerView):
    model = pocos
    properties = ('popup_content',)

GeoDjango/geodjango/core/templates/base.html
{% load static %}

<!doctype html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>Home</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'libs/bootstrap-4.5.0-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    {% block extra_css %}
    {% endblock extra_css %}
</head>
<body>
{% include 'includes/navbar.html' %}

<div class="contrainer-fluid">
    {% block content %}
    {% endblock content %}
</div>
<script src="{%static 'js/jquery-3.1.1.slim.min.js' %}"></script>
<script src="{%static 'js/popper.min.js' %}"></script>
<script src="{%static 'libs/bootstrap-4.5.0-dist/js/bootstrap.min.js' %}"></script>
{% block extra_js %}
{% endblock extra_js %}

</body>
</html>

GeoDjango/geodjango/core/templates/core/index.html
{% extends 'base.html' %}

{% block content %}

    <div class="jumbotron mt-lg-5">
        <div class="container">
            <h1 class="display-3">GeoDjango</h1>
            <p>Projeto de SigWeb com GeoDjango</p>
            <p>
                <a class="btn btn-primary btn-lg" href="#" role="button">
                Acessar o Mapa
                </a>
            </p>
        </div>
    </div>

{% endblock content %}

GeoDjango/geodjango/core/templates/core/mapa.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
    <link href="{% static 'libs/leaflet/leaflet.css' %}" rel="stylesheet">
{% endblock extra_css %}

{% block content %}
    <div id="map"></div>
    <input type="hidden" id="mun_geojson" value="{% url 'mun:mun_geojson' %}">
    <input type="hidden" id="pocos_geojson" value="{% url 'points:poco_geojson' %}">
{% endblock content %}

{% block extra_js %}
    <script src="{% static 'libs/leaflet/leaflet.js'%}"></script>
    <script src="{% static 'js/map.js'%}"></script>
{% endblock extra_js %}

GeoDjango/geodjango/core/templates/includes/navbar.html
<header>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Geodjango</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Mapa</a>
  </div>
</nav>
</header>